# Generated by Django 6.0.3 on 2026-04-10 15:13

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import recommendation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('description', models.TextField(default='')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('transport_mode', models.CharField(choices=[('car', 'Car'), ('jeep', 'Jeep'), ('bus', 'Bus'), ('flight', 'Flight'), ('bike', 'Bike')], default='bus', max_length=20)),
                ('package_type', models.CharField(choices=[('tour', 'Tour'), ('hiking', 'Hiking'), ('sightseeing', 'Sightseeing'), ('adventure', 'Adventure')], default='tour', max_length=20)),
                ('budget', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('distance_km', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_travelers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', validators=[recommendation.models.validate_image])),
                ('description', models.TextField(default='')),
                ('days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='name',
        ),
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='destination',
            name='pName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='adventure',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='culture',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='history',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='sightseeing',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='wildlife',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('pName'), django.db.models.functions.text.Lower('province'), name='unique_destination_case_insensitive'),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.destination'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='end_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_packages', to='recommendation.destination'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='start_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_packages', to='recommendation.destination'),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='recommendation.travelpackage'),
        ),
        migrations.AlterUniqueTogether(
            name='packageitinerary',
            unique_together={('package', 'day_number', 'destination')},
        ),
    ]
