# Generated by Django 6.0.3 on 2026-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_packageitinerary_travelpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitinerary',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
