# Generated by Django 6.0.3 on 2026-04-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_packageitinerary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
