# Generated by Django 6.0.3 on 2026-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='excludes',
            field=models.TextField(blank=True, default='', help_text='Enter items excluded from the package, one per line'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='includes',
            field=models.TextField(blank=True, default='', help_text='Enter items included in the package, one per line'),
        ),
    ]
