# Generated by Django 6.0.3 on 2026-05-13 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_travelpackage_excludes_travelpackage_includes'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='avg_package_price',
            field=models.FloatField(blank=True, help_text='Average package price in NPR for this destination', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_season',
            field=models.CharField(blank=True, help_text="Best season(s) to visit (e.g., 'spring,autumn' or 'winter')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='recommended_visit_days',
            field=models.IntegerField(blank=True, help_text='Recommended number of days to spend at this destination', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
