# Generated by Django 6.0.3 on 2026-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_recommendation_costcomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
