# Generated by Django 6.0.3 on 2026-06-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0010_startlocation_alter_travelpackage_start_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageitinerary',
            name='image',
        ),
    ]
