# Generated by Django 6.0.3 on 2026-07-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0011_remove_packageitinerary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='pName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place Name'),
        ),
    ]
