# Generated by Django 6.0.3 on 2026-07-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0011_remove_packageitinerary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='pName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Place Name'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('payment_method', models.CharField(default='On Arrival', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('not_available', 'Not Available')], default='pending', max_length=30)),
                ('notice', models.TextField(default='You will receive a call for booking confirmation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='recommendation.travelpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
