# Generated by Django 6.0.3 on 2026-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0014_package_rating'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='packagerating',
            new_name='recommendat_package_929d58_idx',
            old_name='recommendation_packag_package_28a0c2_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='khalti_pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
