# Generated by Django 6.0.3 on 2026-07-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0015_rename_recommendation_packag_package_28a0c2_idx_recommendat_package_929d58_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
