# Generated by Django 6.0.3 on 2026-07-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0016_booking_paid_at_booking_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='khalti_pidx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
