# Generated by Django 6.0.3 on 2026-07-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0012_alter_destination_pname'),
        ('recommendation', '0017_remove_booking_khalti_pidx_and_more'),
    ]

    operations = [
    ]
