# Generated by Django 6.0.3 on 2026-04-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_budget_preference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='budget_preference',
            new_name='budget',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='adventure_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='culture_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='history_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sightseeing_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wildlife_weight',
            field=models.FloatField(default=0.2),
        ),
    ]
