# Generated by Django 6.0.3 on 2026-04-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_budget_preference_userprofile_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='adventure_weight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='culture_weight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='history_weight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sightseeing_weight',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wildlife_weight',
        ),
    ]
