# Generated by Django 6.0.3 on 2026-05-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_searchhistory_destination_results_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={},
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='destination_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
